# Generated by Django 3.2.15 on 2022-10-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adj_word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=200, unique=True)),
                ('jp_word', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Adv_word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=200, unique=True)),
                ('jp_word', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='In_word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=200, unique=True)),
                ('jp_word', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Memo_word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=200, unique=True)),
                ('jp_word', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='N_word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=200, unique=True)),
                ('jp_word', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Other_word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=200, unique=True)),
                ('jp_word', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='V_word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=200, unique=True)),
                ('jp_word', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=200)),
            ],
        ),
    ]
