# Generated by Django 3.2.15 on 2022-10-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=200, unique=True)),
                ('jp_word', models.CharField(max_length=200)),
            ],
        ),
    ]
